# - Spawn Location -
# Location where all new or undead members will spawn and respawn.
spawn:
  x: 0
  y: 110
  z: 0
  pitch: 0
  yaw: 0

# - Discord -
# bot-token: Token of the discord bot. Do not share!
# smp-chat-channel: ID of the text channel where in-game messages should be sent.
# change-log-channel: ID of the text channel where change-logs should be published.
# link-channels: IDs of the channels where users can enter their verification codes.
# muted-role: ID of the role users should be given when muted.
# linked-role: ID of the role users should be given when linked/verified.
discord:
  prefix: "-"
  bot-token: "token"
  smp-chat-channel: "000000000000000000"
  smp-chat-topic:
    - "**Online:** %server_online%/%server_max_players%"
    - "**IP:** play.commandgeek.com"
  change-log-channel: "000000000000000000"
  link-channels:
    - "000000000000000000"
  muted-role: "000000000000000000"
  linked-role: "000000000000000000"

#  - Tab Meta -
# header: Text to display above player tab-list. Use placeholders %tps%, %online% and %max%.
# footer:: Text to display below player tab-list. Use placeholders %tps%, %online% and %max%.
tab-meta:
  header:
    - "&7- &dGeekSMP &7-"
    - " "
  footer:
    - " "
    - "&7TPS&8: &d%tps% &8- &7Players&8: &d%online%&8/&d%max%"


# - Settings -
# allow-unplaced-locking: Whether players can lock blocks which do not have any placed data.
# spawn-radius: Radius around spawn in which one cannot take any damage.
# burn: Whether morphed players should burn in daylight (only applies to entities which naturally burn)
# allow-end: Whether players are able to enter an end portal.
# banned-words: Words which will be blocked in chat.
settings:
  allow-unplaced-locking: true
  spawn-radius: 30
  burn: false
  allow-end: false
  banned-words:
    - "Example1"
    - "Example2"

  lockable-blocks:
    - "chest"
    - "trapped_chest"
    - "barrel"
    - "stone_button"
    - "oak_button"
    - "birch_button"
    - "spruce_button"
    - "dark_oak_button"
    - "acacia_button"
    - "warped_button"
    - "crimson_button"
    - "polished_blackstone_button"
    - "lever"
    - "dropper"
    - "dispenser"
    - "hopper"
    - "acacia_pressure_plate"
    - "birch_pressure_plate"
    - "warped_pressure_plate"
    - "crimson_pressure_plate"
    - "oak_pressure_plate"
    - "dark_oak_pressure_plate"
    - "jungle_pressure_plate"
    - "polished_blackstone_pressure_plate"
    - "spruce_pressure_plate"
    - "stone_pressure_plate"
    - "heavy_weighted_pressure_plate"
    - "light_weighted_pressure_plate"

  disabled-commands:
    - "help"
    - "list"
    - "me"
    - "msg"
    - "teammsg"
    - "tell"
    - "tm"
    - "trigger"
    - "w"
    - "plugins"
    - "bukkit:plugins"
    - "pl"
    - "bukkit:pl"

# - Groups -
# All groups on the server.
# Configure each with the options below.

# - Format -
# groups:
#   <name>:
#     <option>:

# - Options -
# color: Main color of the group. Member's names will be changed. (GOLD, AQUA, DARK_RED...)
# prefix: Group prefix for name and tab-list. ("Owner", "&eStaff"...)
# suffix: Group suffix for name and tab-list. ("Tier 1", "&6Level 2"..)
# chat-format: Format for chat messages. If none is provided chat will be disabled for group. Previous prefixes and colors do not apply.
#              Use placeholders %name% and %message%. ("%player% &7> &r%message%", "%player% -  %message%"...)
# translate: Whether messages from group members should translate color codes. (true, false)
# change: If "false", members will never be moved to a different group by the plugin. If "op" members will never be moved as long as they are oped. (true, false, op)
# role: Discord role id a member must have to be moved to this group. Does not apply if a member is in a non-changing group.
# revive-group: Name of the group a member should be moved to when they revive. Only applies to lowest (undead) group.

# Lowest group is default (undead)
groups:
  owner:
    color: GREEN
    prefix: "&a&lOWNER "
    chat-format: "&a&lOWNER &r&a%player% &8> &f%message%"
    translate: true
    status: owner
  special:
    color: AQUA
    prefix: "&b&lSPECIAL "
    chat-format: "&b&lSPECIAL &r&b%player% &8> &f%message%"
    translate: true
    role: "000000000000000000"
  staff:
    color: WHITE
    prefix: "&x&b&5&8&e&f&7&lSTAFF "
    chat-format: "&x&b&5&8&e&f&7&lSTAFF &r&f%player% &8> &f%message%"
    translate: true
    status: staff
    role: "000000000000000000"
  youtuber:
    color: GRAY
    prefix: "&x&f&f&0&0&0&0&lYT "
    chat-format: "&x&f&f&0&0&0&0&lYT &r&7%player% &8> &f%message%"
    role: "000000000000000000"
  mvp:
    color: GRAY
    prefix: "&x&f&f&5&c&6&3&lMVP "
    chat-format: "&x&f&f&5&c&6&3&lMVP &r&7%player% &8> &f%message%"
    translate: true
    role: "000000000000000000"
  vip+:
    color: GRAY
    prefix: "&x&f&f&5&c&6&3&lVIP+ "
    chat-format: "&x&f&f&5&c&6&3&lVIP+ &r&7%player% &8> &f%message%"
    role: "000000000000000000"
  vip:
    color: GRAY
    prefix: "&x&f&f&5&c&6&3&lVIP "
    chat-format: "&x&f&f&5&c&6&3&lVIP &r&7%player% &8> &f%message%"
    role: "000000000000000000"
  tier3:
    color: GRAY
    prefix: "&x&9&0&4&8&f&f&lTIER 3 "
    chat-format: "&x&9&0&4&8&f&f&lTIER 3 &r&7%player% &8> &f%message%"
    translate: true
    role: "000000000000000000"
  tier2:
    color: GRAY
    prefix: "&x&9&0&4&8&f&f&lTIER 2 "
    chat-format: "&x&9&0&4&8&f&f&lTIER 2 &r&7%player% &8> &f%message%"
    role: "000000000000000000"
  tier1:
    color: GRAY
    prefix: "&x&9&0&4&8&f&f&lTIER 1 "
    chat-format: "&x&9&0&4&8&f&f&lTIER 1 &r&7%player% &8> &f%message%"
    role: "000000000000000000"
  guest:
    color: GRAY
    prefix: "&3&lGUEST "
    chat-format: "&3&lGUEST &r&7%player% &8> &f%message%"
    role: "000000000000000000"
  revived:
    color: GRAY
    chat-format: "&7%player% &8> &7%message%"
  undead:
    color: DARK_GRAY
    revive-group: "revived"

# - Morph Selection -
# Item meta for morph selection menu.

# - Format -
# morph-selection:
#   item<number>:
#     <meta>:

# - Meta -
# name: Item name. ("Zombie", "&6Skeleton"...)
# lore: Item lore/description. ("&7Strong, slow movement Speed"...)
# skull: Skull texture value. ("000000000000000000000000...")
morph-selection:
  item1:
    material: PLAYER_HEAD
    name: "&6Zombie"
    lore: "&7Can hold one item. Stronger attack but slower movement speed."
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTZmYzg1NGJiODRjZjRiNzY5NzI5Nzk3M2UwMmI3OWJjMTA2OTg0NjBiNTFhNjM5YzYwZTVlNDE3NzM0ZTExIn19fQ=="
  item2:
    material: PLAYER_HEAD
    name: "&a/verify"
    lore: "&7Are you a &dTwitch Sub &7or &cPatron&7? Do you want to access the Discord Server? No problem! Just type &a/verify &7after selecting your morph, and enter the 4 digit code in the discord server."
  item3:
    material: PLAYER_HEAD
    name: "&6Skeleton"
    lore: "&7Can hold one item. After each bow shot a new arrow will be given."
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzAxMjY4ZTljNDkyZGExZjBkODgyNzFjYjQ5MmE0YjMwMjM5NWY1MTVhN2JiZjc3ZjRhMjBiOTVmYzAyZWIyIn19fQ=="
