name: GeekSMP
author: CommandGeek
main: com.commandgeek.geeksmp.Main

version: '${version}'
api-version: 1.13

softdepend: [PlaceholderAPI]
depend: [ProtocolLib]

commands:
  reloadsmp:
    aliases: [rsmp]
  revive:
    aliases: []
  unrevive:
    aliases: []
  mute:
    aliases: []
  mutelist:
    aliases: [mlist]
  unmute:
    aliases: []
  ban:
    aliases: []
  banlist:
    aliases: [blist]
  unban:
    aliases: []
  die:
    aliases: [suicide]
  gmc:
    aliases: []
  gms:
    aliases: []
  gma:
    aliases: []
  gmsp:
    aliases: []
  rules:
    aliases: [rule]
  info:
    aliases: []
  help:
    aliases: [?]
  code:
    aliases: [verify, link]
  discord:
    aliases: [invite]
  twitch:
    aliases: [stream]
  map:
    aliases: [webmap]
  changelog:
    aliases: []
  unlink:
    aliases: []
  purgechat:
    aliases: [clearchat]
  purgeteams:
    aliases: [clearteams]
  feed:
    aliases: []
  heal:
    aliases: []
  tphere:
    aliases: [tph]
  tp:
    aliases: []
  msg:
    aliases: [message]
  reply:
    aliases: [r]
  msgtoggle:
    aliases: [messagetoggle]
  spy:
    aliases: []
  track:
    aliases: []
  seeinv:
    aliases: [invsee]
  lookup:
    aliases: [linked]
  playerinfo:
    aliases: [pinfo]
  stats:
    aliases: []
  trust:
    aliases: []
  trustlist:
    aliases: [tlist]
  untrust:
    aliases: []
  pet:
    aliases: []
  inspect:
    aliases: [i]
  ip:
    aliases: []
  afk:
    aliases: []
  reason:
    aliases: []
  bypass:
    aliases: []
  broadcast:
    aliases: [alert]
  locktool:
    aliases: [getlocktool, givelocktool, tool, givetool, gettool]
  debug:
    aliases: []
  trash:
    aliases: [disposal]
  day:
    aliases: [sunrise, midday, sun]
  night:
    aliases: [midnight, sunset, moon]


permissions:
  geeksmp.command.reloadsmp:
    default: op
  geeksmp.command.revive:
    default: op
  geeksmp.command.unrevive:
    default: op
  geeksmp.command.mute:
    default: op
  geeksmp.command.mutelist:
    default: op
  geeksmp.command.unmute:
    default: op
  geeksmp.command.ban:
    default: op
  geeksmp.command.banlist:
    default: op
  geeksmp.command.unban:
    default: op
  geeksmp.command.die:
    default: true
  geeksmp.command.gmc:
    default: op
  geeksmp.command.gms:
    default: op
  geeksmp.command.gma:
    default: op
  geeksmp.command.gmsp:
    default: op
  geeksmp.command.rules:
    default: true
  geeksmp.command.info:
    default: true
  geeksmp.command.help:
    default: true
  geeksmp.command.code:
    default: true
  geeksmp.command.discord:
    default: true
  geeksmp.command.twitch:
    default: true
  geeksmp.command.map:
    default: true
  geeksmp.command.changelog:
    default: op
  geeksmp.command.unlink:
    default: true
  geeksmp.command.purgechat:
    default: op
  geeksmp.command.purgeteams:
    default: op
  geeksmp.command.feed:
    default: op
  geeksmp.command.heal:
    default: op
  geeksmp.command.tphere:
    default: op
  geeksmp.command.tp:
    default: op
  geeksmp.command.msg:
    default: true
  geeksmp.command.reply:
    default: true
  geeksmp.command.msgtoggle:
    default: true
  geeksmp.command.spy:
    default: op
  geeksmp.command.track:
    default: true
  geeksmp.command.seeinv:
    default: op
  geeksmp.command.lookup:
    default: true
  geeksmp.command.playerinfo:
    default: true
  geeksmp.command.stats:
    default: op
  geeksmp.command.trust:
    default: true
  geeksmp.command.trustlist:
    default: true
  geeksmp.command.untrust:
    default: true
  geeksmp.command.pet:
    default: op
  geeksmp.command.inspect:
    default: op
  geeksmp.command.ip:
    default: op
  geeksmp.command.afk:
    default: true
  geeksmp.command.reason:
    default: op
  geeksmp.command.bypass:
    default: op
  geeksmp.command.broadcast:
    default: op
  geeksmp.command.locktool:
    default: op
  geeksmp.command.debug:
    default: op
  geeksmp.command.trash:
    default: op
  geeksmp.command.day:
    default: op
  geeksmp.command.night:
    default: op
