# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on:
  push:
    branches: [ master ]
    paths:
      - 'gradle/**'
      - 'src/**'
      - '/build.gradle'
      - '/gradlew'
      - '/gradlew.bat'
      - '/settings.gradle'
#  pull_request:
#    paths:
#      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 16
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - name: Build jar with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: "actions/upload-artifact@v2.2.3"
        with:
          name: "GeekSMP"
          path: build/libs
